########## Testcase 0: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(SeparateChainingHashST.java:69)
	at SeparateChainingHashST.get(SeparateChainingHashST.java:120)
	at SeparateChainingHashST.contains(SeparateChainingHashST.java:104)
	at Solution.main(Solution.java:21)
----------------------------------------
########## Testcase 1: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(SeparateChainingHashST.java:69)
	at SeparateChainingHashST.get(SeparateChainingHashST.java:120)
	at SeparateChainingHashST.contains(SeparateChainingHashST.java:104)
	at Solution.main(Solution.java:21)
----------------------------------------
########## Testcase 2: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(SeparateChainingHashST.java:69)
	at SeparateChainingHashST.get(SeparateChainingHashST.java:120)
	at SeparateChainingHashST.contains(SeparateChainingHashST.java:104)
	at Solution.main(Solution.java:21)
----------------------------------------
########## Testcase 3: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(SeparateChainingHashST.java:69)
	at SeparateChainingHashST.get(SeparateChainingHashST.java:120)
	at SeparateChainingHashST.contains(SeparateChainingHashST.java:104)
	at Solution.main(Solution.java:21)
----------------------------------------
########## Testcase 4: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(SeparateChainingHashST.java:69)
	at SeparateChainingHashST.get(SeparateChainingHashST.java:120)
	at SeparateChainingHashST.contains(SeparateChainingHashST.java:104)
	at Solution.main(Solution.java:21)
----------------------------------------
########## Testcase 5: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at SeparateChainingHashST.hash(SeparateChainingHashST.java:69)
	at SeparateChainingHashST.get(SeparateChainingHashST.java:120)
	at SeparateChainingHashST.contains(SeparateChainingHashST.java:104)
	at Solution.main(Solution.java:21)
----------------------------------------
